FLASK_APP=app

FLASK_DEBUG=1

FLASK_TESTING=1

FLASK_ENV=development

FLASK_APP=app.py

FLASK_SQLALCHEMY_TRACK_MODIFICATIONS=false

FLASK_UPLOAD_FOLDER=static/uploads/images

FLASK_MAX_CONTENT_PATH=300M

FLASK_API_VERSION=0.1

FLASK_OPENAPI_VERSION=3.0.2

FLASK_OPENAPI_URL_PREFIX=/api

FLASK_OPENAPI_JSON_PATH=docs/openapi.json

FLASK_OPENAPI_SWAGGER_UI_PATH=/docs

FLASK_OPENAPI_SWAGGER_UI_VERSIO=3

FLASK_OPENAPI_SWAGGER_UI_URL=https://cdn.jsdelivr.net/npm/swagger-ui-dist/

FLASK_API_TITLE='Flask Rest api demo'


FLASK_JWT_AUTH_URL_RULE=/api/auth/login

FLASK_JWT_AUTH_USERNAME_KEY=email
